---
title: "Arbeidskrav Vitenskapsteori"
output: html_document
bibliography: references.bib
---

# Arbeidskrav i vitenskapsteori

### Oppgave 1

Falsifikasjonisme Karl Popper var en analytisk filosof, som utarbeidet et falsifiserbarhetskriterium. Popper ble inspirert til denne tankegangen gjennom tre ulike kilder, demarkasjonsproblemet, induksjonsproblemet og risikable forutsigelser. Demarkasjonsproblemet danner grunnlaget for utfordringen med å skille vitenskap og pseudovitenskap fra hverandre. Induksjonsproblemet stiller et spørsmål om hvordan man kan vite at en vitenskapelig teori er sann. Dette så ikke Popper på som et problem da han mente at vitenskapelige teorier ikke kan bekreftes. Det siste som inspirerte popper er risikable forutsigelser som er vanskelig eller umulige å falsifisere [@alnes2018].

Poppers demarkasjonskriterium kommer fra ønsket å skille vitenskapelig teori fra ikke-vitenskapelig teori også kalt pseudovitenskap **(Dellsén, 2021, lysark 7**). Løsningen på dette mente han ikke kunne komme fra å verifisere teorier, da dette kan være vanskelig eller umulig. Løsningen på dette problemet blir da å falsifisere teorier, ergo å bekrefte at de er usanne, eller feil. Et eksempel på dette er en teori om at alle hunder er hvite. Det er umulig å bekrefte at det aldri har vært hunder som har en annen farge, eller at det noen gang kommer til å være hunder som har en annen farge. Dette er årsaken til at Popper mener det er umulig å bekrefte en teori, da man aldri kan vite hva som har vært eller hva som kommer. Ved å bruke samme eksempel kan man falsifisere teorien når man oppdager en hund som ikke er hvit. Falsifikasjon er da kriteriet som kan skille vitenskap fra pseudovitenskap, i følge Popper [@okasha2016].

Popper ytret at vitenskapelige teorier som ikke er mulig å falsifisere, hvor man uansett kan få de empiriske bevisene til å passe inn i teorien, skaper lite troverdighet og at disse ikke skulle godtas som vitenskapelig teori [@okasha2016]. Popper [@1969] forklarer dette med teorier fra Marx, Freud og Adler, som han syns var utfordrende at skulle aksepteres som vitenskapelige teorier. Teorier som er mulig å falsifisere (dette betyr ikke at de trenger å være usanne) er mer troverdig, og viktige teorier når de blir testet.

Samir Okasha [@okasha2016] (2016, s. 55-57) beskriver flere utfordringer ved Poppers falsifiserbarhetskriterium. En av utfordringene Okasha beskriver er hvordan dette kriteriet kan påvirke hvordan verden blir oppfattet hvis man hele tiden skal avkrefte teorier. Med dette mener han at vitenskapelige teorier som ikke kan falsifiseres likevel kan ha eller hatt stor påvirkning på hvordan den vitenskapelige teoriene kan utvikle seg. Disse teoriene kan og bidra til nye viktige oppdagelser innenfor tematikken. Videre beskriver Okasha problematikken med å skulle definere hvile teorier som kan kalles vitenskap og ikke-vitenskap, og hvorfor dette ikke er nødvendig. Et av eksemplene han trekker frem er hvordan det nesten er umulig at alle observasjoner stemmer med en vitenskapelig teori. Videre beskriver han hvor vid og bred vitenskapen er, og hvor ulik alle teoriene er. Han beskriver vitenskap som ulike teorier som har mange fellestrekk, og at selv uten alle fellestrekkene vil dette være vitenskapelige teorier med bekreftende observasjoner (Okasha, 2016, s. 59). Jeg mener Okasha har et godt poeng i at det ikke er så viktig å skille mellom vitenskap og psudovitenskap som Popper ønsket. Som Okasha påpeker har det blitt gjort viktig oppdagelser i lyset av en teori som viste seg å ikke stemme, og det er derfor ikke like viktig med det markante skillet, men at begrepet er litt flytende.

### Oppgave 2 

HD-metoden og abduksjon/Bayesisme Hypotetisk deduktiv metode kan deles i to ulike kontekster for ulike faser av utvikling av teorien, oppdagelseskonteksten og begrunnelseskonteksten. Oppdagelseskonteksten er miljøet der teorien eller hypotesen blir oppdaget. I følge Hempel finnes det ingen bestemt metode å finne opp nye ideer, men de kan for eksempel oppstå fra fantasier eller ulike observasjoner man gjør (Dellsén, 2021, lysark 28). Dette kan forekommer tilfeldig, eller hvis man prøver å finne en forklaring eller årsak på et bestemt problem. Dette er begrunnelseskonteksten. Hempel (1966, s. 12) beskriver at det ikke er noen fasit på hvordan nye teorier blir oppdaget, men at det skje på mange ulike måter.

Den logiske strukturen i hypotetisk deduktiv metode er å bekrefte om en idé stemmer ved å teste den, gjennom å observere konsekvensene. Metoden er delt inn i fire ulike faser for bekreftelse av en ny teori (Dellsén, 2021, lysark 29). Fase en er å oppdage en ny teori eller lete etter en hypotese på et problem. Andre fase er å dedusere de empiriske konsekvensene fra teorien. Dette vil si at hypotesen kan være «det finnes liv på Jupiter». Dette vil si at de empiriske konsekvensene av dette vil være at det er oksygen på Jupiter, det er vann på Jupiter osv. Ved fase 3 undersøker man, og samler inn data for å se om hypotesen stemmer, og om innsamlede data stemmer med de empiriske konsekvensene. For eksempelet beskrevet over vil dette bety at man må teste om det er oksygen, vann osv på Jupiter. Hvis de ikke stemmer forkaster man, eller endre hypotesen for å komme nærmere en ny idé eller hypotese som forklarer problemstillingen. Når man eventuelt har innsamlede data som stemmer med de empiriske konsekvensene kan man konkludere. Da har man til en viss grad fått en induktiv bekreftelse av hypotesen. Dette fordi det kan være andre årsaker som fører til endringen eller årsakssammenheng som hypotesen ikke tar for seg. Dette vil ikke bety at den hypotesen som man først har kommet frem til ikke stemmer, men at det er andre årsaksforhold som og kan påvirke (Hempel, 1966, s. 11).

Abduksjon er en vitenskapelig metode man bruker for å bekrefte teorier. Denne metoden handler om å dra slutninger til den beste forklaringen til et nytt fenomen eller ny data. For å finne dette trenger man flere ulike teorier som har forskjellige årsaksforklaringer på dataen. Det er flere elementer som kan bidra til at en forklaring er bedre. Hvis teorien har forklaringskraft, forklarer flere forskjellige data, vil dette styrke teorien. Det samme gjelder hvis teorien har en enklere årsaksforklaring, forklarer dataen ut fra færre ting (Dellsén, 2021, lysark 20). Dette vil si at i abduksjon må man sammenligne flere ulike forklaringer til samme fenomen, og finne den som best forklarer dataen.

For å sammenligne med hypotetisk deduksjon som oppgir en hypotese med ulike empiriske konsekvenser tilbyr abduksjon flere hypoteser eller forklaringer. Noe som kan være en svakhet med HD metoden er at det kan være flere konsekvenser og årsaker som kan underligge ved en «korrekt» hypotese enn det man ser. En annen svakhet med HD metoden er at svarene man får fra dataen kan være en tilfeldighet, som gjør at det virker som man bekrefter hypotesen, men det er egentlig andre bedre forklaringer på problemet. Dette er et av problemene som gjorde at abduksjon ble skapt. Ved abduksjon ønsker man å se på ulike forklaringer og finne den metoden som gir den beste forklaringen til problemet. Dette betyr at det abduksjon ønsker å se flere forklaringene til det samme problemet for å finne den beste forklaringen.

### Oppgave 3 

Replikasjonskrisen Bird beskriver replikasjonskrisen som foregår innenfor forskningsfeltet, som et stort problem som kan ha flere negative konsekvenser for vitenskapelig allmenhet, som at troverdigheten er synkende. Bird bruker tre ulike konsept for å forklare replikasjonskrisen. Disse er type-I feil, type-II feil og basefrekvensfeilen. Type-I feil, er å akseptere en hypotese eller teori som ikke stemmer (Bird, 2018, s. 5-6). Et eksempel på dette kan være en promilletest som viser at en sjåfør kjører med promille, selv om sjåføren ikke har drukket alkohol. Type-II feil er å forkaste en hypotese eller en teori som faktisk stemmer. Dette kan være at en promille test viser at en påvirket sjåfør ikke har promille. Basefrekvensfeilen er en feil som forekommer når man fokuserer på at en viss sannsynlighet forekommer ved en test, som å se på hvor mange sjåfører som kjører ruspåvirket. Hvis 50 av 1000 mennesker som blir testet for rus, tester positivt, men bare 10 faktisk kjørte ruspåvirket, vil det si at det var 40 falsk-positive tester. Fenomenet påpeker da at når man konkluderer med hvor mange tester som slo ut for rus, og ikke tar hensyn for hvor mange falsk-positive tester det var forekommer basefrekvensfeilen. Det er færre folk som ikke kjører påvirket, så da er sannsynligheten for at de daller i den 5% feilen større enn at de faktisk kjører ruspåvirket. I dette eksempelet vil basefrekvensfeilen oppstå fordi frekvensen av ruspåvirket sjåfører mot ikke-ruspåvirket sjåfører i befolkningen generelt er lav. Bird påpeker hvordan dette slår ut i forskning ved å bruke dette fenomenet. Satt i sammenheng med forskning viser Bird til hvordan dette vil slå ut på hypotesetesting, og hvordan falsk-positive, og falsk-negative forkastninger vil forekomme. Dette fordi man ikke tar høyde for den generelle forekomsten i befolkningen når man tester på for små grupper (Bird, 2018, s. 6).

En annen forklaringer som blir nevnt ved replikasjonskrisen er publikasjons bias. Publikasjons bias forekommer når resultater blir skjevt fremstilt for å avgjøre om en studie skal publiseres eller ikke. Dette forekommer først og fremst ved å oftere publisere studier med statistisk signifikante resultater. Dette vil da bety at studier som er gjennomført hvor resultatene ikke er statistisk signifikante, resultatene ikke stemmer med hypotesen ikke vil bli publisert (Bird, 2018, s.21).

Andre forklaringer til replikasjonskrisen er at flere studier ikke blir gjennomført på tilstrekkelig måte for å kunne repetere forsøket, eller at studiet mangler validitet, ergo at studiet ikke gjennomføres på den måten det var planlagt at det skulle gjøres, eller gjennomført slik det er beskrevet at det er gjort. En annen forklaring som blir nevnt er hacking av resultater for å få en studie til å se bedre ut enn det er (Bird, 2018, s. 23)

Bird presenterer en mer akademisk forklaring enn de andre årsakene som blir nevnt. Om forskere driver med svindel eller praktiserer dårlig gjennomføring i studiene blir vanskelig å kunne konkludere med. Bird kommer med en forklaring som viser hvordan hypotesetesting kan tolkes feil, eller aksepteres med stor mulighet for type-I eller type-II feil. Forklaringene som har blitt nevnt er alle aksepterbare, og mulige, og det blir vanskelig å konkludere at den ene er bedre enn den andre, men Bird presenterer en mer troverdig forklaring.
